syntax = "proto3";

package auth.v1;

import "google/protobuf/empty.proto";
import "user/v1/user.proto";
import "session/v1/session.proto";

option go_package = "github.com/sakura-skytree/sakura-airlines-contracts/gen/go/auth/v1;authv1";

service AuthService {
  rpc Register(RegisterRequest) returns(RegisterResponse);

  rpc Login(LoginRequest) returns(LoginResponse);

  rpc Logout(LogoutRequest) returns(google.protobuf.Empty);

  rpc GetAuthUser(GetAuthUserRequest) returns(GetAuthUserResponse);
}

message RegisterRequest {
  string email = 1;
  string password = 2;
  session.v1.SessionMetadata session_metadata = 3;
}

message RegisterResponse {
  user.v1.User user = 1;
  string session_id = 2;
}

message LoginRequest {
  string email = 1;
  string password = 2;
  session.v1.SessionMetadata session_metadata = 3;
}

message LoginResponse {
  user.v1.User user = 1;
  string session_id = 2;
}

message LogoutRequest {
  string session_id = 1;
}

message GetAuthUserRequest {
 string session_id = 1;
}

message GetAuthUserResponse {
  optional user.v1.User user = 1;
  bool ok = 2;
}